#!/bin/bash

exec 2>&1

export ZOOBINDIR="{{pkg.path}}/bin/"
export ZOOCFGDIR="{{pkg.svc_config_path}}"
export JAVA_HOME="{{pkgPathFor "core/jre8"}}"
export ZOOMAIN=org.apache.zookeeper.server.quorum.QuorumPeerMain
export ZOOCFGDIR=/etc/zookeeper/conf
export ZOOCFG=/etc/zookeeper/conf/zoo.cfg
export ZOO_LOG_DIR=/var/log/zookeeper
export ZOO_LOG4J_PROP=INFO,ROLLINGFILE
export JMXLOCALONLY=true

{{pkg.path}}/bin/zkEnv.sh

exec {{pkg.path}}/bin/zkServer.sh start-foreground
